title: lukas zamora # name of the site
author: lukas zamora # name of site's author
email: lukaspzamora@gmail.com # email of site's author
url: https://lukaszamora.github.io # root address of the site
description: > # description of the site (multiple lines allowed)
  aspriring data analyst -- music lover.

permalink: /:slug.html

favicon: "./logo.png" # relative path to site's favicon
# goat_counter: "yoursitename" # put your GoatCounter name if you want to use GoatCounter analytics

remote_theme: riggraz/no-style-please # if you are using GitHub Pages, change it to remote_theme: riggraz/no-style-please

theme_config:
  back_home_text: "<-" # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: true # show blog description in home page

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag